# Generated by Django 5.0.6 on 2024-05-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0015_book_borrowed_by_book_is_borrowed_alter_book_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrowed_by',
        ),
        migrations.AddField(
            model_name='book',
            name='borrowed_by_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
